version: '3'

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.0.1/16

services:
  frontend:
    build: GraphExplorer
    image: graphfront
    ports:
      - "8000:5000"