version: '3.7'

services:
  frontend:
    build: ./GraphExplorer
    image: graphfront:latest
    ports:
      - "8000:5000"
    volumes:
      - shared-data:/code/public/data

  backend:
    build: ./GraphMaker
    image: graphback:latest
    volumes:
      - shared-data:/code/public/data 

volumes:
  shared-data:
