version: '3.7'

services:
  backend:
    build: ./GraphMaker
    image: graphback:latest
    volumes:
      - shared-data:/code/public/data
    env_file:
      - ./GraphMaker/.env
  
  frontend:
    build: ./GraphExplorer
    image: graphfront:latest
    ports:
      - "5000:5000"
    volumes:
      - shared-data:/code/public/data
    depends_on:
      backend:
        condition: service_started

volumes:
  shared-data:
